added logo and timer screen
malikrahey/DrinkUp pull request #1
Opened 2023-10-23 20:58 UTC by dchicasduena

changes:
- added logo
- changed buttons a bit
- added timer screen

2023-10-24 22:32 UTC, malikrahey requested changes

2023-10-24 23:10 UTC, dchicasduena commented on styles.js
>    }
this was for something else I was trying to do and ended up not using it so its fine to delete

2023-10-25 01:13 UTC, malikrahey approved these changes

2023-10-25 01:13 UTC, malikrahey commented on screens/TimerScreen.js
> +                    {screen == "1" ? (
screen === 1

2023-10-25 01:13 UTC, malikrahey commented on screens/TimerScreen.js
> +                        ) : screen == "2" ? (
screen === 2

2023-10-25 01:13 UTC, merged