Back Button and Card Changes
malikrahey/DrinkUp pull request #3
Opened 2023-11-09 18:17 UTC by dchicasduena

Added a back button to the main game and changed the look of the cards

2023-11-09 18:31 UTC, malikrahey requested changes

2023-11-09 18:31 UTC, malikrahey commented on screens/GameScreen.js
> +      <TouchableOpacity onPress={handleNext} className={`${bgColor} flex items-center h-full justify-center`} style={styles.card}>
do this with tailwind instead, makes it cleaner

2023-11-09 18:31 UTC, malikrahey commented on styles.js
>  });
🙊

2023-11-13 15:58 UTC, dchicasduena commented
changed to tailwind

2023-11-14 20:57 UTC, malikrahey requested changes

2023-11-14 20:57 UTC, malikrahey commented on screens/HomeScreen.js
>        <Image style={styles.logo} source={logo}></Image>
tailwind

2023-11-14 20:57 UTC, malikrahey commented on screens/TimerScreen.js
>            return <Text style={{ fontSize: '80em' }} className="text-center font-bold">Drink!</Text>;
tailwind, only reason to ever use the styles class is for the AndroidSafeArea really cause we can't do that easily with tailwind

2023-11-14 20:57 UTC, malikrahey commented on screens/TimerScreen.js
>            return <Text style={{ fontSize: '80em' }} className="text-center font-bold">Drink!</Text>;
you can do text-[80em] if none of the other presets work for it too

2023-11-14 23:43 UTC, closed without merging